name: Python package

on: [push]

permissions:
  contents: read # This is required for actions/checkout

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.12"]
        builder: ["buildjet-2vcpu-ubuntu-2204", "buildjet-2vcpu-ubuntu-2204-arm"]
#        builder: ["buildjet-2vcpu-ubuntu-2204"]

    runs-on: ${{ matrix.builder }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev]"
        env:
          PIP_EXTRA_INDEX_URL: https://pypi.moya.app/moya/stable
      -
        name: Run lint
        run: |
          poe lint
      -
        name: Test with pytest
        # A 250 exit status sometimes randomly comes from the coverage report black magic
        run: |
          poe test -vv
